import { useEffect, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../api.js';
import { useToast } from '../ctx.jsx';
import ArticleCard from '../components/ArticleCard.jsx';
import { Cover } from '../components/Cover.jsx';
import Icon from '../components/Icon.jsx';
import { catColor, timeAgo } from '../util.js';

const paras = (t) => { const s = t.split(/(?<=[.!?])\s+/), out = []; for (let i = 0; i < s.length; i += 3) out.push(s.slice(i, i + 3).join(' ')); return out; };

export default function ArticleView() {
  const { id } = useParams();
  const toast = useToast();
  const [a, setA] = useState(null);
  const [err, setErr] = useState('');
  const [flags, setFlags] = useState({ saved: false, liked: false });
  const [prog, setProg] = useState(0);
  const acc = useRef(0), last = useRef(Date.now());

  // Track visible reading time and report it when the reader leaves.
  useEffect(() => {
    setA(null); setErr(''); window.scrollTo(0, 0); acc.current = 0; last.current = Date.now();
    api(`/articles/${id}`).then((d) => { setA(d); setFlags({ saved: d.saved, liked: d.liked }); }).catch((e) => setErr(e.message));
    api(`/articles/${id}/view`, { method: 'POST' }).catch(() => {});
    const onVis = () => { if (document.hidden) acc.current += Date.now() - last.current; else last.current = Date.now(); };
    const send = () => {
      const ms = acc.current + (document.hidden ? 0 : Date.now() - last.current);
      if (ms > 3000) api(`/articles/${id}/read`, { method: 'POST', body: { dwell: Math.round(ms / 1000) }, keepalive: true }).catch(() => {});
    };
    const onScroll = () => { const h = document.documentElement.scrollHeight - innerHeight; setProg(h > 0 ? Math.min(100, (scrollY / h) * 100) : 0); };
    document.addEventListener('visibilitychange', onVis); window.addEventListener('beforeunload', send); window.addEventListener('scroll', onScroll, { passive: true });
    return () => { document.removeEventListener('visibilitychange', onVis); window.removeEventListener('beforeunload', send); window.removeEventListener('scroll', onScroll); send(); };
  }, [id]);

  const toggle = async (kind) => {
    const key = kind === 'save' ? 'saved' : 'liked', cur = flags[key];
    setFlags({ ...flags, [key]: !cur });
    try { await api(`/articles/${id}/${kind}`, { method: 'POST' }); toast(kind === 'save' ? (cur ? 'Removed from saved' : 'Saved to your reading list') : cur ? 'Like removed' : 'Liked. We will show more like this.'); }
    catch { setFlags({ ...flags, [key]: cur }); toast('Could not update. Try again.'); }
  };

  if (err) return <div className="empty"><h3>Story not available</h3><p>{err}</p><Link className="btn" to="/feed">Back to your feed</Link></div>;
  if (!a) return <div className="article"><div className="skel"><div className="cover tall" /></div></div>;

  return (
    <>
      <div className="progress" style={{ width: `${prog}%` }} />
      <article className="article">
        <Link to="/feed" className="small back">Back to feed</Link>
        <div className="kicker"><i className="dot" style={{ background: catColor(a.category) }} /><strong>{a.category}</strong><span>{a.source}</span><span>{timeAgo(a.publishedAt)}</span><span>{a.readingTime} min read</span></div>
        <h1 className="serif">{a.title}</h1>
        <div className="row meta-row">
          <button className={`btn ${flags.saved ? 'active' : ''}`} onClick={() => toggle('save')} aria-pressed={flags.saved}><Icon name="bookmark" fill={flags.saved} /> {flags.saved ? 'Saved' : 'Save'}</button>
          <button className={`btn ${flags.liked ? 'active' : ''}`} onClick={() => toggle('like')} aria-pressed={flags.liked}><Icon name="heart" fill={flags.liked} /> {flags.liked ? 'Liked' : 'Like'}</button>
          {a.url && <a className="btn" href={a.url} target="_blank" rel="noreferrer"><Icon name="external" /> Original source</a>}
          <span className={`tag ${a.sentiment?.label}`} title={`Sentiment score ${a.sentiment?.score}`}>Tone: {a.sentiment?.label}</span>
        </div>
        <Cover a={a} className="tall" />

        <section className="summary">
          <h2>Quick summary</h2>
          <ul>{a.summary.map((s, i) => <li key={i}>{s}</li>)}</ul>
          <p className="muted small">Generated by Lumen's extractive summarizer.</p>
        </section>

        <div className="prose serif">{paras(a.content).map((p, i) => <p key={i}>{p}</p>)}</div>

        <div className="kw"><span className="muted small">Key topics</span>{a.keywords.map((k) => <Link key={k} className="chip static" to={`/explore?q=${k}`}>{k}</Link>)}</div>
      </article>

      {a.similar?.length > 0 && (
        <section className="similar">
          <h2>More like this</h2>
          <div className="grid">{a.similar.map((s) => <ArticleCard key={s._id} a={{ ...s, reasons: [`${s.similarity}% similar content`] }} />)}</div>
        </section>
      )}
    </>
  );
}
